-- IMAGE LINK GENERATOR PRO - SUPABASE
-- Jalankan seluruh script ini di Supabase Dashboard > SQL Editor.

create table if not exists public.image_upload_history (
  id bigint generated by default as identity primary key,
  staff_name text not null check (char_length(trim(staff_name)) between 1 and 80),
  file_name text,
  image_url text not null,
  uploaded_at timestamptz not null default now()
);

create index if not exists image_upload_history_uploaded_at_idx
  on public.image_upload_history (uploaded_at desc);

create index if not exists image_upload_history_staff_name_idx
  on public.image_upload_history (staff_name);

alter table public.image_upload_history enable row level security;

drop policy if exists "public can read image history" on public.image_upload_history;
create policy "public can read image history"
on public.image_upload_history for select
to anon, authenticated using (true);

drop policy if exists "public can insert image history" on public.image_upload_history;
create policy "public can insert image history"
on public.image_upload_history for insert
to anon, authenticated
with check (
  char_length(trim(staff_name)) between 1 and 80
  and char_length(image_url) > 0
);

grant select, insert on table public.image_upload_history to anon, authenticated;

-- Aktifkan Realtime untuk sinkronisasi riwayat antar perangkat.
alter publication supabase_realtime add table public.image_upload_history;
