-- TVTOTO IMAGE LINK GENERATOR PRO/MAX
-- Run in Supabase SQL Editor.

alter table public.image_upload_history
  add column if not exists file_hash text;

create index if not exists image_upload_history_file_hash_idx
  on public.image_upload_history(file_hash);

create table if not exists public.image_history_audit (
  id bigint generated by default as identity primary key,
  action text not null,
  history_id bigint,
  staff_name text,
  file_name text,
  image_url text,
  actor_user_id uuid,
  actor_email text,
  created_at timestamptz not null default now()
);

alter table public.image_history_audit enable row level security;

revoke all on table public.image_history_audit from anon, authenticated;
grant select on table public.image_history_audit to authenticated;

drop policy if exists "Only admins can read audit" on public.image_history_audit;
create policy "Only admins can read audit"
on public.image_history_audit
for select
to authenticated
using ((select public.is_image_history_admin()));

create or replace function public.log_image_history_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_email text;
begin
  select email into actor_email
  from auth.users
  where id = (select auth.uid());

  insert into public.image_history_audit(
    action, history_id, staff_name, file_name, image_url,
    actor_user_id, actor_email
  )
  values(
    'DELETE', old.id, old.staff_name, old.file_name, old.image_url,
    (select auth.uid()), actor_email
  );
  return old;
end;
$$;

drop trigger if exists trg_image_history_delete_audit on public.image_upload_history;
create trigger trg_image_history_delete_audit
after delete on public.image_upload_history
for each row execute function public.log_image_history_delete();

-- Make sure only admins can delete.
drop policy if exists "Only admins can delete image history" on public.image_upload_history;
create policy "Only admins can delete image history"
on public.image_upload_history
for delete
to authenticated
using ((select public.is_image_history_admin()));

grant delete on public.image_upload_history to authenticated;
